version: '3'
services:
  web2:
    image: crm:latest3
    build: .
    ports:
      - "4000:5000"
      - "5431:5432"
      - "6378:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:2701172004@host.docker.internal:5432/Crm
      - SESSION_REDIS_URL=redis://host.docker.internal:6379
      - SECRET_KEY=5313b16ca203b539824a13add8495dcd
    volumes:
      - .:/app

  web:
    image: crm:latest3
    build: .
    ports:
      - "5000:5000"
      - "5432:5432"
      - "6379:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:2701172004@host.docker.internal:5432/Crm
      - SESSION_REDIS_URL=redis://host.docker.internal:6379
      - SECRET_KEY=5313b16ca203b539824a13add8495dcd
    volumes:
      - .:/app

  nginx:
    image: crmnginx:latest3
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - web2
